for i=3:8
    [maxC,bestLag] = CorCalculator(T.glucose,T{:,i});
    fprintf("Cor maxim intre glucoza si %s este %.3f, la lag = %d (%d minute)\n", ...
        T.Properties.VariableNames{i}, ...
        maxC, ...
        bestLag, ...
        5*bestLag)
end